name: zc_desktop_flutter
description: Zuri Chat Desktop App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  logger: ^1.0.0
<<<<<<< HEAD
=======

>>>>>>> b3ce203934cbf5e49f588802419b3108b802b9d2
  bitsdojo_window: ^0.1.1+1


  get_it: ^7.2.0



  # local storage
<<<<<<< HEAD
=======

>>>>>>> b3ce203934cbf5e49f588802419b3108b802b9d2
  shared_preferences: ^2.0.7
  stacked: ^2.2.5
  stacked_services: null
  zcdesk_ui:
    path: packages/zcdesk_ui


dev_dependencies:
  build_runner: null
  flutter_test:
    sdk: flutter
  stacked_generator: ^0.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
<<<<<<< HEAD
    - assets/images/facebook.svg
    - assets/images/google.svg
    - assets/images/twitter.svg
=======

    - assets/images/facebook.svg
    - assets/images/google.svg
    - assets/images/twitter.svg

>>>>>>> b3ce203934cbf5e49f588802419b3108b802b9d2
    - assets/images/widgetImages/
 

 
<<<<<<< HEAD
=======

>>>>>>> b3ce203934cbf5e49f588802419b3108b802b9d2
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
